name: pypi push
'on':
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'
      - run: python -m pip install -q twine build && python3 -m build && python3 -m twine upload dist/* -u __token__ -p "${{ secrets.PYPI_API_TOKEN }}"
